variables:
    CONTAINER_NAME: benchmark-front
    IMAGE_NAME: alayahamza/benchmark-front:latest

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - npm ci
    - npm run build
    - docker build -t $IMAGE_NAME .
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
    - docker push $IMAGE_NAME

deploy-benchmark-front:
  stage: deploy
  script:
    - if [ $(docker ps | grep $CONTAINER_NAME | wc -l) -gt 0 ]; then docker stop $CONTAINER_NAME; fi
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
    - docker run --rm -d -p 4444:4444 --name $CONTAINER_NAME $IMAGE_NAME
