variables:
    CONTAINER_NAME: benchmark-front
    IMAGE_NAME: alayahamza/benchmark-front:latest

cache:
  paths:
    - /dist

stages:
  - npm-build
  - docker-build
  - deploy

npm-build-dist:
  stage: npm-build
  script:
    - npm ci
    - npm run build
  artifacts:
      paths:
        - dist/

docker-build-image:
  stage: docker-build
  script:
    - docker build -t $IMAGE_NAME .
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
    - docker push $IMAGE_NAME
  artifacts:
      paths:
        - dist/

deploy-benchmark-front:
  stage: deploy
  script:
    - if [ $(docker ps | grep $IMAGE_NAME | wc -l) -gt 0 ]; then docker stop $CONTAINER_NAME; fi
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
    - docker run --rm -d -p 4444:4444 --name $CONTAINER_NAME $IMAGE_NAME
